### ISSUE TITLE
nats-webui  Add Server always show Unreachable？

### ISSUE THREAD

**Issue by lddlww** [sphqxe/NATS-WebUI#59]
screenshot display：
![image](https://github.com/sphqxe/NATS-WebUI/assets/27006237/c7abda30-3d82-4698-a262-7ad12f3fc654)

telnet is ok
```
telnet 10.59.126.249 4222
Trying 10.59.126.249...
Connected to 10.59.126.249.
Escape character is '^]'.
INFO {"server_id":"NCFRVBR7PWL7CSW2JCOOVPX3A5AXX5HEK7WCABQTR4PPD45PE6VH45WR","server_name":"NCFRVBR7PWL7CSW2JCOOVPX3A5AXX5HEK7WCABQTR4PPD45PE6VH45WR","version":"2.8.4","proto":1,"git_commit":"66524ed","go":"go1.17.10","host":"0.0.0.0","port":4222,"headers":true,"tls_required":true,"max_payload":1048576,"client_id":57,"client_ip":"172.18.6.161"}
```

am i missing something?

**Comment by srikrishnacj** [comment]
I am also facing problem

**Comment by 7medina** [comment]
same

**Comment by asoorm** [comment]
same here

**Comment by al32-rs** [comment]
same

**Comment by wangrongzeng** [comment]
same

**Comment by gpratik** [comment]
Anyone knows the alternative, it's not working for me as well

**Comment by avivace** [comment]
same

**Comment by symccann** [comment]
Has anyone managed to crack this nut?

**Comment by Chebura** [comment]
same (localhost, docker desktop)

**Comment by paul-asvb** [comment]
same

**Comment by NiclasThobaben** [comment]
same. But as the last commit is already 4 years old, I guess there won't be anything happening.

**Comment by thielj** [comment]
I've [fixed some issues](https://github.com/thielj/NATS-WebUI) and produced a smallish alpine-based image.

To persist settings, mount a volume to /data. For example:

```
# https://github.com/thielj/NATS-WebUI/pkgs/container/nats-webui
mkdir ./nats-webui && chown 1000:1000
docker run --rm -p 8080:80 -v "${PWD}/nats-webui:/data" ghcr.io/thielj/nats-webui:latest
```

**Comment by autokilla47** [comment]
> I've [fixed some issues](github.com/thiel/NATS-WebUI) and produced a smallish alpine-based image.

404

**Comment by thielj** [comment]
@autokilla47 Sorry URL was messed up. Try: 
https://github.com/thielj/NATS-WebUI or go directly to
https://github.com/thielj/NATS-WebUI/pkgs/container/nats-webui

**Comment by zn-luo** [comment]
> I've [fixed some issues](https://github.com/thielj/NATS-WebUI) and produced a smallish alpine-based image.
> 
> To persist settings, mount a volume to /data. For example:
> 
> ```
> # https://github.com/thielj/NATS-WebUI/pkgs/container/nats-webui
> mkdir ./nats-webui && chown 1000:1000
> docker run --rm -p 8080:80 -v "${PWD}/nats-webui:/data" ghcr.io/thielj/nats-webui:latest
> ```

it can not run with bind error， as follows:

thread 'main' panicked at 'error binding to 0.0.0.0:80: error creating server listener: Permission denied (os error 13)', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by zn-luo** [comment]
> screenshot display： ![image](https://private-user-images.githubusercontent.com/27006237/275415625-c7abda30-3d82-4698-a262-7ad12f3fc654.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODc4OTYsIm5iZiI6MTcyNzY4NzU5NiwicGF0aCI6Ii8yNzAwNjIzNy8yNzU0MTU2MjUtYzdhYmRhMzAtM2Q4Mi00Njk4LWEyNjItN2FkMTJmM2ZjNjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA5MTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNmQzZDEwOTllZjMyMzM0YzFjMDFkZmRmMTZmNTVjYjBmZjBjZTFmMmJmNTYwMjA0ZmZmNjRlNWQ1NTdlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lt97t8MhBnU8_rGYGyPrTqLl_ALK90DYdxWcLckr5Mw)
> 
> telnet is ok
> 
> ```
> telnet 10.59.126.249 4222
> Trying 10.59.126.249...
> Connected to 10.59.126.249.
> Escape character is '^]'.
> INFO {"server_id":"NCFRVBR7PWL7CSW2JCOOVPX3A5AXX5HEK7WCABQTR4PPD45PE6VH45WR","server_name":"NCFRVBR7PWL7CSW2JCOOVPX3A5AXX5HEK7WCABQTR4PPD45PE6VH45WR","version":"2.8.4","proto":1,"git_commit":"66524ed","go":"go1.17.10","host":"0.0.0.0","port":4222,"headers":true,"tls_required":true,"max_payload":1048576,"client_id":57,"client_ip":"172.18.6.161"}
> ```
> 
> am i missing something?

same

**Comment by thielj** [comment]
> > I've [fixed some issues](https://github.com/thielj/NATS-WebUI) and produced a smallish alpine-based image.
> > 
> > To persist settings, mount a volume to /data. For example:
> > 
> > ```
> > # https://github.com/thielj/NATS-WebUI/pkgs/container/nats-webui
> > mkdir ./nats-webui && chown 1000:1000
> > docker run --rm -p 8080:80 -v "${PWD}/nats-webui:/data" ghcr.io/thielj/nats-webui:latest
> > ```
> 
> it can not run with bind error， as follows:
> 
> thread 'main' panicked at 'error binding to 0.0.0.0:80: error creating server listener: Permission denied (os error 13)', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/macros.rs:16:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Have you actually used my version here?

https://github.com/thielj/NATS-WebUI/pkgs/container/nats-webui

The failed bind is probably an indication that something else is already listening on the port.

**Comment by zn-luo** [comment]
你的邮件我已收到，谢谢！祝百事可乐！

**Comment by zn-luo** [comment]
I use the version nats-webui:v0.1.2 with docker pull.
The port should not be occupied by something  else because container networking is not host.
error as picture
![1111](https://github.com/user-attachments/assets/c24d140c-d0d1-48d3-a38a-d81b023708ab)

**Comment by thielj** [comment]
@zn-luo Do you have SELinux or something else in place that prevents container applications without root privileges to bind to ports lower than 1024?

**Comment by thielj** [comment]
@zn-luo Do you have SELinux or something else in place that prevents container applications without root privileges to bind to ports lower than 1024?

Maybe run `cat /proc/sys/net/ipv4/ip_unprivileged_port_start` inside the container.

**Comment by zn-luo** [comment]
> the



> @zn-luo Do you have SELinux or something else in place that prevents container applications without root privileges to bind to ports lower than 1024?
> 
> Maybe run `cat /proc/sys/net/ipv4/ip_unprivileged_port_start` inside the container.

docker can not start up, so i can't run  `cat /proc/sys/net/ipv4/ip_unprivileged_port_start` inside the container.
But it seem there is not  /proc/sys/net/ipv4/ip_unprivileged_port_start inside the container.
shown as picture.
![nats-webui](https://github.com/user-attachments/assets/6a42ff78-e142-4a6f-8331-b13c841bc9e9)

**Comment by zn-luo** [comment]
> unprivile



> @zn-luo Do you have SELinux or something else in place that prevents container applications without root privileges to bind to ports lower than 1024?
> 
> Maybe run `cat /proc/sys/net/ipv4/ip_unprivileged_port_start` inside the container.


It can not run with --sysctl "net.ipv4.ip_unprivileged_port_start=1024",
show as picture.
![nats-webui111](https://github.com/user-attachments/assets/af562c9e-d3a5-4a48-8427-1ae0c821d315)

**Comment by thielj** [comment]
@zn-luo I'm afraid there are only two options here: (1) fix your setup so the container can bind to ports lower than 1024; or (2) change the app to bind to e.g. port 8080 instead - or use an environment variable to override the default.

See https://github.com/thielj/NATS-WebUI/blob/0d6e4b0c1b499aa6013c4b07eee0c7d94784660d/src/main.rs#L162

**Comment by zn-luo** [comment]
> @zn-luo I'm afraid there are only two options here: (1) fix your setup so the container can bind to ports lower than 1024; or (2) change the app to bind to e.g. port 8080 instead - or use an environment variable to override the default.
> 
> See https://github.com/thielj/NATS-WebUI/blob/0d6e4b0c1b499aa6013c4b07eee0c7d94784660d/src/main.rs#L162

I can run up a container with ghcr.io/thielj/nats-webui:v0.1.2 in docker Version 27.3.1,  but after adding a nat server ,the status is Unreachable

**Comment by zn-luo** [comment]
It works for me.
I fixed the problem with fixing the tls_timeout datatype.
Fixed the tls_timeout type from i64 to f64.
And fixed missing field to Option, for example fix server_name to Option.
The error is shown in the following picture.
![Image](https://github.com/user-attachments/assets/99ee1832-d120-4b1c-8b75-88d6a07406ae)
![Image](https://github.com/user-attachments/assets/19094623-65fa-4825-8354-46e6f87aec7b)

**Comment by gpratik** [comment]
@zn-luo - I am getting the same error.  Do you have any forked branch with updated changes?a

![Image](https://github.com/user-attachments/assets/4ff314d4-d609-4056-8413-ca951455cb0e)

![Image](https://github.com/user-attachments/assets/a09ee2fa-9dce-4db9-959e-c426bdb40740)

**Comment by zn-luo** [comment]
你的邮件我已收到，谢谢！祝百事可乐！

**Comment by zn-luo** [comment]
> [@zn-luo](https://github.com/zn-luo) - I am getting the same error. Do you have any forked branch with updated changes?a
> 
> ![Image](https://github.com/user-attachments/assets/4ff314d4-d609-4056-8413-ca951455cb0e)
> 
> ![Image](https://github.com/user-attachments/assets/a09ee2fa-9dce-4db9-959e-c426bdb40740)

Your problem seems to be a network problem, not a code problem.
Fored branch https://github.com/zn-luo/NATS-WebUI

**Comment by thielj** [comment]
> Fored branch https://github.com/zn-luo/NATS-WebUI

Can you submit a pull request maybe?

**Comment by 10thfloor** [comment]
Your `nats.conf` looks like this for local dev: 

```
host: "0.0.0.0"

websocket {
    host: "0.0.0.0"
    port: 8080
    no_tls: true
}

authorization {
    token: "keyboardcat"
}
```

Start NATS (no Docker): `nats-server -js -store_dir ./data -c nats.conf -m 8222` (use whatever `data` directory you want)

Start WebUI Docker: ` docker run --rm -p 8888:80 -v "${PWD}/data" --add-host host.docker.internal:host-gateway ghcr.io/thielj/nats-webui:latest`

This is the solution for `Connection Refused` error.

Then you can `Add Server` with 
host: `host.docker.internal` 
ports default
auth: `keyboardcat`

This works, however there's a JSON parsing error now: 
```
2025-03-27T20:09:35.230Z ERROR [nats_webui::datatypes] Failed to parse VARZ JSON: Error("missing field `host`", line: 24, column: 12)
2025-03-27T20:09:35.230Z ERROR [nats_webui] Failed to fetch varz: JsonError(Error("missing field `host`", line: 24, column: 12))
2025-03-27T20:09:35.230Z DEBUG [nats_webui] Finished fetching server varz
```

We need to add: 

```rust
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
pub struct WebSocket {
    host: String,
    port: u16,
    no_tls: bool,
}
```
To: https://github.com/sphqxe/NATS-WebUI/blob/835b844e20ca509e6d90c9dd482750c9f828eae1/src/datatypes.rs#L34

And update anywhere else this data-structure is used. 

I'm not a RUST dev, so maybe someone else wants to try this out?

**Comment by gpratik** [comment]
@10thfloor—Correct. There were two issues. The connection issue was caused by hosting the NATS server in a Docker container. The other issue was resolved by updating the ServerVarz struct in datatypes.rs to match the actual JSON structure returned by the NATS server monitoring endpoint.


I checked each data returned by it, based on that, I commented that code, and it worked.

`Invoke-RestMethod -Uri "http://localhost:8222/varz?json=true" | ConvertTo-Json`

I have submitted pull to origin repo but it's owners choice to merge.

I have forked my change here. This works well.

https://github.com/gpratik/NATS-WebUI

**Comment by clndwhr** [comment]
> [@10thfloor](https://github.com/10thfloor)—Correct. There were two issues. The connection issue was caused by hosting the NATS server in a Docker container. The other issue was resolved by updating the ServerVarz struct in datatypes.rs to match the actual JSON structure returned by the NATS server monitoring endpoint.
> 
> I checked each data returned by it, based on that, I commented that code, and it worked.
> 
> `Invoke-RestMethod -Uri "http://localhost:8222/varz?json=true" | ConvertTo-Json`
> 
> I have submitted pull to origin repo but it's owners choice to merge.
> 
> I have forked my change here. This works well.
> 
> https://github.com/gpratik/NATS-WebUI

You have a typo in your web/src/components/Client.vue file line 106, where protocol gets set, the `ws:"` has an additional `"` character in the string

**Comment by zn-luo** [comment]
你的邮件我已收到，谢谢！祝百事可乐！
